from spyrim_map import SpyrimMap
import random

class ProMap(SpyrimMap):
    def __init__(self, x, y):
        self.__map = []
        self.__dragons_quantity = 20
        super().__init__(x, y)
    
    def create_map (self):
        for j in range(super().y):
            self.__map.append([])
            for i in range(super().x):
                self.__map[j].append(f"{j}-{i}")
                
        self.set_ragnar_mountain()
        self.set_frostfall_village()
        self.set_whiterun_village()
        self.set_woods()
        self.set_river_1()
        self.set_talos_lake()
        self.set_soltitude_village()
        self.set_sovngarde_village()
        self.set_jerall_mountains()
        self.set_ancient_mountains()
        self.set_dragons(self.__dragons_quantity)
        SpyrimMap.map = self.__map
    
    def set_ragnar_mountain(self):
        self.__map[5][7] = "ragnar mountain"
        self.__map[5][8] = "ragnar mountain"
        self.__map[6][6] = "ragnar mountain"
        self.__map[6][7] = "ragnar mountain"
        self.__map[6][8] = "ragnar mountain"
        self.__map[7][6] = "ragnar mountain"
        self.__map[7][7] = "ragnar mountain"
        self.__map[8][7] = "ragnar mountain"
        self.__map[8][8] = "ragnar mountain"
    
    def set_frostfall_village(self):
        self.__map[1][11] = "frostfall"
        self.__map[1][12] = "frostfall"
        self.__map[1][13] = "frostfall"
        self.__map[2][12] = "frostfall"
        self.__map[2][13] = "frostfall"
        self.__map[3][11] = "frostfall"
        self.__map[3][12] = "frostfall"
        self.__map[3][13] = "frostfall"
        self.__map[4][11] = "frostfall"
        self.__map[4][12] = "frostfall"
        self.__map[5][12] = "frostfall"
    
    def set_whiterun_village(self):
        self.__map[5][2] = "whiterun"
        self.__map[5][3] = "whiterun"
        self.__map[6][1] = "whiterun"
        self.__map[6][2] = "whiterun"
        self.__map[6][3] = "whiterun"
        self.__map[7][2] = "whiterun"
        self.__map[7][3] = "whiterun"
        self.__map[8][1] = "whiterun"
        self.__map[8][2] = "whiterun"
        self.__map[8][3] = "whiterun"
        self.__map[9][2] = "whiterun"
        self.__map[9][3] = "whiterun"
        self.__map[10][3] = "whiterun"
    
    def set_woods(self):
        self.__map[10][6] = "woods"
        self.__map[10][7] = "woods"
        self.__map[10][8] = "woods"
        self.__map[10][10] = "woods"
        self.__map[10][12] = "woods"
        self.__map[10][13] = "woods"
        self.__map[11][8] = "woods"
        self.__map[11][10] = "woods"
        self.__map[11][11] = "woods"
        self.__map[11][13] = "woods"
        self.__map[11][14] = "woods"
        self.__map[12][5] = "woods"
        self.__map[12][6] = "woods"
        self.__map[12][7] = "woods"
        self.__map[12][8] = "woods"
        self.__map[12][9] = "woods"
        self.__map[12][10] = "woods"
        self.__map[12][11] = "woods"
        self.__map[12][12] = "woods"
        self.__map[12][13] = "woods"
        self.__map[12][14] = "woods"
        self.__map[13][6] = "woods"
        self.__map[13][7] = "woods"
        self.__map[13][8] = "woods"
        self.__map[13][9] = "woods"
        self.__map[13][10] = "woods"
        self.__map[13][11] = "woods"
        self.__map[13][12] = "woods"
        self.__map[13][13] = "woods"
        self.__map[13][14] = "woods"
        self.__map[14][7] = "woods"
        self.__map[14][8] = "woods"
        self.__map[14][9] = "woods"
        self.__map[14][10] = "woods"
        self.__map[14][11] = "woods"
        self.__map[14][12] = "woods"
        self.__map[14][13] = "woods"
        self.__map[14][14] = "woods"
        self.__map[15][7] = "woods"
        self.__map[15][10] = "woods"
        self.__map[15][13] = "woods"
        self.__map[15][14] = "woods"
        self.__map[15][15] = "woods"
        self.__map[16][6] = "woods"
        self.__map[16][14] = "woods"
        self.__map[16][15] = "woods"
        self.__map[17][7] = "woods"

        # Second woods
        self.__map[3][26] = "woods"
        self.__map[4][25] = "woods"
        self.__map[4][26] = "woods"
        self.__map[4][27] = "woods"
        self.__map[5][24] = "woods"
        self.__map[5][25] = "woods"
        self.__map[5][26] = "woods"
        self.__map[5][27] = "woods"
        self.__map[5][28] = "woods"
        self.__map[6][26] = "woods"
        self.__map[6][27] = "woods"
        self.__map[6][28] = "woods"
        self.__map[7][25] = "woods"
        self.__map[7][26] = "woods"
        self.__map[7][27] = "woods"
        self.__map[7][28] = "woods"
        self.__map[7][29] = "woods"
        self.__map[8][25] = "woods"
        self.__map[8][26] = "woods"
        self.__map[8][27] = "woods"
        self.__map[8][28] = "woods"
        self.__map[8][29] = "woods"
        self.__map[9][24] = "woods"
        self.__map[9][25] = "woods"
        self.__map[9][26] = "woods"
        self.__map[9][27] = "woods"
        self.__map[9][28] = "woods"
        self.__map[9][29] = "woods"
        self.__map[10][24] = "woods"
        self.__map[10][26] = "woods"
        self.__map[10][27] = "woods"
        self.__map[10][28] = "woods"
        self.__map[10][29] = "woods"
        self.__map[11][24] = "woods"
        self.__map[11][26] = "woods"
        self.__map[11][27] = "woods"
        self.__map[11][28] = "woods"
        self.__map[11][29] = "woods"
        self.__map[12][26] = "woods"
        self.__map[12][27] = "woods"
        self.__map[12][28] = "woods"
        self.__map[12][29] = "woods"
        self.__map[13][25] = "woods"
        self.__map[13][26] = "woods"
        self.__map[13][27] = "woods"
        self.__map[13][28] = "woods"
        self.__map[14][25] = "woods"
        self.__map[14][26] = "woods"
        self.__map[14][27] = "woods"
        self.__map[14][28] = "woods"
        self.__map[15][25] = "woods"
        self.__map[15][26] = "woods"
        self.__map[15][27] = "woods"
        self.__map[15][28] = "woods"
        self.__map[15][29] = "woods"
        self.__map[16][24] = "woods"
        self.__map[16][25] = "woods"
        self.__map[16][26] = "woods"
        self.__map[16][27] = "woods"
        self.__map[16][28] = "woods"
        self.__map[17][24] = "woods"
        self.__map[17][26] = "woods"
        self.__map[17][27] = "woods"
        self.__map[17][28] = "woods"
        self.__map[18][24] = "woods"
        self.__map[18][26] = "woods"
        self.__map[18][27] = "woods"
        self.__map[18][28] = "woods"
        self.__map[19][26] = "woods"
        self.__map[19][27] = "woods"
        self.__map[19][28] = "woods"
        self.__map[20][23] = "woods"
        self.__map[20][24] = "woods"
        self.__map[20][25] = "woods"
        self.__map[20][26] = "woods"
        self.__map[20][27] = "woods"
        self.__map[20][28] = "woods"
        self.__map[21][24] = "woods"
        self.__map[21][25] = "woods"
        self.__map[21][26] = "woods"
        self.__map[21][27] = "woods"
        self.__map[22][26] = "woods"
    
    def set_river_1(self):
        self.__map[2][0] = "river"
        self.__map[2][1] = "river"
        self.__map[2][2] = "river"
        self.__map[1][2] = "river"
        self.__map[1][3] = "river"
        self.__map[1][4] = "river"
        self.__map[2][4] = "river"
        self.__map[2][5] = "river"
        self.__map[2][6] = "river"
        self.__map[1][6] = "river"
        self.__map[0][6] = "river"

        # Second river
        self.__map[25][15] = "river"
        self.__map[26][4] = "river"
        self.__map[26][5] = "river"
        self.__map[26][6] = "river"
        self.__map[26][9] = "river"
        self.__map[26][10] = "river"
        self.__map[26][13] = "river"
        self.__map[26][14] = "river"
        self.__map[26][15] = "river"
        self.__map[26][16] = "river"
        self.__map[27][0] = "river"
        self.__map[27][1] = "river"
        self.__map[27][2] = "river"
        self.__map[27][3] = "river"
        self.__map[27][4] = "river"
        self.__map[27][5] = "river"
        self.__map[27][6] = "river"
        self.__map[27][7] = "river"
        self.__map[27][8] = "river"
        self.__map[27][9] = "river"
        self.__map[27][10] = "river"
        self.__map[27][11] = "river"
        self.__map[27][12] = "river"
        self.__map[27][13] = "river"
        self.__map[27][14] = "river"
        self.__map[27][15] = "river"
        self.__map[27][16] = "river"
        self.__map[27][17] = "river"
        self.__map[27][18] = "river"
        self.__map[27][19] = "river"
        self.__map[27][20] = "river"
        self.__map[28][0] = "river"
        self.__map[28][1] = "river"
        self.__map[28][2] = "river"
        self.__map[28][6] = "river"
        self.__map[28][7] = "river"
        self.__map[28][13] = "river"
        self.__map[28][20] = "river"
        self.__map[28][21] = "river"
        self.__map[29][1] = "river"
        self.__map[29][2] = "river"
        self.__map[29][19] = "river"
        self.__map[29][20] = "river"
    
    def set_talos_lake(self):
        self.__map[0][15] = "talos lake"
        self.__map[0][17] = "talos lake"
        self.__map[0][18] = "talos lake"
        self.__map[1][15] = "talos lake"
        self.__map[1][17] = "talos lake"
        self.__map[1][18] = "talos lake"
        self.__map[1][19] = "talos lake"
        self.__map[2][16] = "talos lake"
        self.__map[2][17] = "talos lake"
        self.__map[2][18] = "talos lake"
        self.__map[2][19] = "talos lake"
        self.__map[2][20] = "talos lake"
        self.__map[3][15] = "talos lake"
        self.__map[3][16] = "talos lake"
        self.__map[3][17] = "talos lake"
        self.__map[3][18] = "talos lake"
        self.__map[3][19] = "talos lake"
        self.__map[4][16] = "talos lake"
        self.__map[4][17] = "talos lake"
        self.__map[4][18] = "talos lake"
        self.__map[4][19] = "talos lake"
        self.__map[4][20] = "talos lake"
        self.__map[4][21] = "talos lake"
        self.__map[5][16] = "talos lake"
        self.__map[5][19] = "talos lake"
        self.__map[5][20] = "talos lake"
    
    def set_soltitude_village(self):
        self.__map[7][18] = "soltitude"
        self.__map[8][18] = "soltitude"
        self.__map[9][18] = "soltitude"
        self.__map[10][18] = "soltitude"
        self.__map[11][18] = "soltitude"
        self.__map[12][18] = "soltitude"
        self.__map[13][18] = "soltitude"
        self.__map[14][18] = "soltitude"
        self.__map[15][18] = "soltitude"
        self.__map[16][18] = "soltitude"
        self.__map[7][17] = "soltitude"
        self.__map[7][20] = "soltitude"
        self.__map[7][21] = "soltitude"
        self.__map[8][17] = "soltitude"
        self.__map[8][21] = "soltitude"
        self.__map[9][19] = "soltitude"
        self.__map[9][21] = "soltitude"
        self.__map[10][19] = "soltitude"
        self.__map[10][20] = "soltitude"
        self.__map[10][21] = "soltitude"
        self.__map[11][17] = "soltitude"
        self.__map[11][19] = "soltitude"
        self.__map[12][21] = "soltitude"
        self.__map[12][21] = "soltitude"
        self.__map[13][16] = "soltitude"
        self.__map[13][17] = "soltitude"
        self.__map[13][19] = "soltitude"
        self.__map[13][20] = "soltitude"
        self.__map[13][21] = "soltitude"
        self.__map[13][22] = "soltitude"
        self.__map[14][17] = "soltitude"
        self.__map[14][19] = "soltitude"
        self.__map[14][20] = "soltitude"
        self.__map[14][21] = "soltitude"
        self.__map[14][22] = "soltitude"
        self.__map[15][19] = "soltitude"
        self.__map[15][22] = "soltitude"
        self.__map[16][21] = "soltitude"
        self.__map[17][20] = "soltitude"
        self.__map[17][21] = "soltitude"
    
    def set_sovngarde_village(self):
        self.__map[16][10] = "sovngarde"
        self.__map[17][9] = "sovngarde"
        self.__map[17][10] = "sovngarde"
        self.__map[18][8] = "sovngarde"
        self.__map[18][9] = "sovngarde"
        self.__map[18][10] = "sovngarde"
        self.__map[18][11] = "sovngarde"
        self.__map[19][8] = "sovngarde"
        self.__map[19][9] = "sovngarde"
        self.__map[19][10] = "sovngarde"
        self.__map[19][11] = "sovngarde"
        self.__map[19][12] = "sovngarde"
        self.__map[20][6] = "sovngarde"
        self.__map[20][7] = "sovngarde"
        self.__map[20][8] = "sovngarde"
        self.__map[20][9] = "sovngarde"
        self.__map[20][10] = "sovngarde"
        self.__map[20][11] = "sovngarde"
        self.__map[20][12] = "sovngarde"
        self.__map[21][7] = "sovngarde"
        self.__map[21][8] = "sovngarde"
        self.__map[21][9] = "sovngarde"
        self.__map[21][10] = "sovngarde"
        self.__map[21][11] = "sovngarde"
        self.__map[21][12] = "sovngarde"
        self.__map[21][13] = "sovngarde"
        self.__map[22][9] = "sovngarde"
        self.__map[22][10] = "sovngarde"
        self.__map[22][11] = "sovngarde"
        self.__map[22][12] = "sovngarde"
        self.__map[22][13] = "sovngarde"
        self.__map[23][8] = "sovngarde"
        self.__map[23][9] = "sovngarde"
        self.__map[23][10] = "sovngarde"
        self.__map[23][12] = "sovngarde"
        self.__map[23][13] = "sovngarde"
        self.__map[23][14] = "sovngarde"
        self.__map[24][10] = "sovngarde"
        self.__map[24][13] = "sovngarde"
    
    def set_jerall_mountains(self):
        self.__map[15][1] = "jerall mountains"
        self.__map[16][1] = "jerall mountains"
        self.__map[16][2] = "jerall mountains"
        self.__map[16][3] = "jerall mountains"
        self.__map[17][1] = "jerall mountains"
        self.__map[17][2] = "jerall mountains"
        self.__map[17][3] = "jerall mountains"
        self.__map[18][1] = "jerall mountains"
        self.__map[18][2] = "jerall mountains"
        self.__map[18][3] = "jerall mountains"
        self.__map[18][4] = "jerall mountains"
        self.__map[19][2] = "jerall mountains"
        self.__map[19][3] = "jerall mountains"
    
    def set_ancient_mountains(self):
        self.__map[19][20] = "ancient mountains"
        self.__map[20][20] = "ancient mountains"
        self.__map[20][21] = "ancient mountains"
        self.__map[21][19] = "ancient mountains"
        self.__map[21][20] = "ancient mountains"
        self.__map[22][20] = "ancient mountains"
        self.__map[22][22] = "ancient mountains"
        self.__map[23][20] = "ancient mountains"
        self.__map[23][21] = "ancient mountains"
        self.__map[23][22] = "ancient mountains"
        self.__map[24][19] = "ancient mountains"
        self.__map[24][20] = "ancient mountains"
        self.__map[24][21] = "ancient mountains"
        self.__map[24][22] = "ancient mountains"
        self.__map[24][23] = "ancient mountains"
        self.__map[24][26] = "ancient mountains"
        self.__map[24][27] = "ancient mountains"
        self.__map[25][19] = "ancient mountains"
        self.__map[25][21] = "ancient mountains"
        self.__map[25][22] = "ancient mountains"
        self.__map[25][23] = "ancient mountains"
        self.__map[25][24] = "ancient mountains"
        self.__map[25][26] = "ancient mountains"
        self.__map[25][27] = "ancient mountains"
        self.__map[26][22] = "ancient mountains"
        self.__map[26][23] = "ancient mountains"
        self.__map[26][24] = "ancient mountains"
        self.__map[26][25] = "ancient mountains"
        self.__map[26][26] = "ancient mountains"
        self.__map[26][28] = "ancient mountains"
        self.__map[27][23] = "ancient mountains"
        self.__map[27][24] = "ancient mountains"
        self.__map[27][25] = "ancient mountains"
        self.__map[27][26] = "ancient mountains"
        self.__map[28][25] = "ancient mountains"
        self.__map[28][27] = "ancient mountains"

    def set_dragons(self, quantity):
        for i in range(quantity):
            x = random.randint(0, super().x - 1)
            y = random.randint(0, super().y - 1)
            self.__map[y][x] = "DRAGON"
